#!/usr/bin/env bash
# install nginx on remote server

apt-get update
apt-get upgrade -y
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
listen 80;
    server_name localhost;
    location / {
        root /etc/nginx/html;
        index index.html;
    }
    location /redirect {
        return 301 https://www.hayesholberton.tech;
    }
    error_page 404 /404.html;
}" > /etc/nginx/sites-available/default
sudo service nginx restart
