#!/usr/bin/env bash
# Script that displays numbers from 1 to 100.

for ((x=1;x<=100;x++))
do
	if ((x % 3 == 0 && x % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((x % 3 ==0))
	then
		echo "Fizz"
	elif ((x % 5 ==0))
	then
		echo "Buzz"
	else
		echo "$x"
	fi
done
