#!/user/bin/env bash
# This is a script using while loop along with if command to display Best School and hi
i=1
while [ $i -le 10 ]
do
if [ $i = 9 ]
then
	echo "Best School"
	echo "Hi"
else
	echo "Best School"
fi
i=$(( i + 1 ))
done
