#!/usr/bin/env bash
# Script displaying the time 12:59 using while loop

HOUR=0

while [ $HOUR -le 12 ]
	do
	echo "Hour:$HOUR"
	(( HOUR++ )) 
done 

MINUTE=1

while [ $MINUTE -le 59 ]
	do
	echo "Minute:$MINUTE"
	(( MINUTE++ ))
done
