#!/usr/bin/env bash
# Update and Install nginx on remote server

apt-get update
apt-get upgrade -y
apt-get install -y nginx
# create Hello World html file
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
# config nginx to listen on port 80
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html;
    add_header x-Server-by $HOSTNAME;
    location /redirect_me {
        return 301 https://www.hayesholberton.tech;
    }
    error_page 404 /404.html;
    location = /404 {
    root /etc/nginx/html;
    internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
